import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';

/** Filesystem boundary used by deterministic typegen artifact commits. */
export type TypegenArtifactFileSystem = {
  readonly mkdir: (path: string) => Promise<void>;
  readonly readFile: (path: string) => Promise<string>;
  readonly rename: (source: string, destination: string) => Promise<void>;
  readonly rm: (path: string) => Promise<void>;
  readonly writeFile: (path: string, content: string) => Promise<void>;
};

type ArtifactInspection =
  | { readonly status: 'malformed' }
  | { readonly status: 'unsupported-version'; readonly version: number }
  | { readonly status: 'valid'; readonly version: number };

/** Stable non-mutating comparison result for an existing typegen target. */
export type TypegenArtifactCheck =
  | { readonly status: 'MALFORMED' }
  | { readonly status: 'MISSING' }
  | { readonly status: 'STALE' }
  | { readonly status: 'UNCHANGED' }
  | { readonly status: 'UNSUPPORTED_VERSION'; readonly version: number };

/** Stable write action reported after an atomic typegen artifact commit. */
export type TypegenArtifactWriteAction = 'CREATE' | 'UNCHANGED' | 'UPDATE';

const NODE_FILE_SYSTEM: TypegenArtifactFileSystem = {
  async mkdir(path) {
    await mkdir(path, { recursive: true });
  },
  readFile: (path) => readFile(path, 'utf8'),
  rename,
  async rm(path) {
    await rm(path, { force: true });
  },
  async writeFile(path, content) {
    await writeFile(path, content, { encoding: 'utf8', flag: 'wx' });
  },
};

let temporaryFileSequence = 0;

function isMissingFileError(error: unknown): boolean {
  return typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT';
}

async function readExistingArtifact(
  outputPath: string,
  fileSystem: TypegenArtifactFileSystem,
): Promise<string | undefined> {
  try {
    return await fileSystem.readFile(outputPath);
  } catch (error: unknown) {
    if (isMissingFileError(error)) {
      return undefined;
    }
    throw error;
  }
}

/**
 * Compares an existing artifact with expected generated bytes without writing.
 *
 * @param outputPath Target artifact path.
 * @param expectedSource Authoritative generated source.
 * @param inspect Structural artifact classifier.
 * @param fileSystem Filesystem boundary used to read the target.
 * @returns A stable unchanged, missing, stale, malformed, or unsupported-version result.
 */
export async function checkTypegenArtifact(
  outputPath: string,
  expectedSource: string,
  inspect: (source: string) => ArtifactInspection,
  fileSystem: TypegenArtifactFileSystem = NODE_FILE_SYSTEM,
): Promise<TypegenArtifactCheck> {
  const existingSource = await readExistingArtifact(outputPath, fileSystem);
  if (existingSource === undefined) {
    return { status: 'MISSING' };
  }
  if (existingSource === expectedSource) {
    return { status: 'UNCHANGED' };
  }

  const inspection = inspect(existingSource);
  if (inspection.status === 'malformed') {
    return { status: 'MALFORMED' };
  }
  if (inspection.status === 'unsupported-version') {
    return { status: 'UNSUPPORTED_VERSION', version: inspection.version };
  }
  return { status: 'STALE' };
}

/**
 * Atomically publishes generated source while skipping byte-identical rewrites.
 *
 * @param outputPath Target artifact path.
 * @param source Complete generated source to publish.
 * @param fileSystem Filesystem boundary used for the atomic replacement.
 * @returns The stable create, update, or unchanged action.
 */
export async function writeTypegenArtifact(
  outputPath: string,
  source: string,
  fileSystem: TypegenArtifactFileSystem = NODE_FILE_SYSTEM,
): Promise<TypegenArtifactWriteAction> {
  const existingSource = await readExistingArtifact(outputPath, fileSystem);
  if (existingSource === source) {
    return 'UNCHANGED';
  }

  await fileSystem.mkdir(dirname(outputPath));
  temporaryFileSequence += 1;
  const temporaryPath = join(
    dirname(outputPath),
    `.${basename(outputPath)}.${String(process.pid)}.${String(temporaryFileSequence)}.tmp`,
  );
  let committed = false;
  try {
    await fileSystem.writeFile(temporaryPath, source);
    await fileSystem.rename(temporaryPath, outputPath);
    committed = true;
  } finally {
    if (!committed) {
      await fileSystem.rm(temporaryPath);
    }
  }

  return existingSource === undefined ? 'CREATE' : 'UPDATE';
}
