// Generated by scripts/generate-published-internal-dependencies.mjs during the CLI build.
/** Per-package release ranges for all published starter dependencies except the generator CLI itself. */
export const PUBLISHED_INTERNAL_DEPENDENCIES = {
  "@fluojs/config": "^1.0.4",
  "@fluojs/core": "^1.1.0",
  "@fluojs/di": "^2.0.0",
  "@fluojs/http": "^2.0.1",
  "@fluojs/microservices": "^1.0.5",
  "@fluojs/platform-bun": "^2.0.0",
  "@fluojs/platform-cloudflare-workers": "^1.0.5",
  "@fluojs/platform-deno": "^1.1.0",
  "@fluojs/platform-express": "^1.1.0",
  "@fluojs/platform-fastify": "^1.0.9",
  "@fluojs/platform-nodejs": "^1.0.6",
  "@fluojs/react": "^0.1.0",
  "@fluojs/runtime": "^2.0.1",
  "@fluojs/testing": "^2.0.0",
  "@fluojs/validation": "^1.0.6",
  "@fluojs/vite": "^1.0.7"
} as const;
