import { Container } from '@fluojs/di';
import { describe, expect, it } from 'vitest';

import {
  Controller,
  createDispatcher,
  createHandlerMapping,
  type FrameworkRequest,
  type FrameworkResponse,
  Get,
  Head,
  Put,
} from '../index.js';

type TestResponse = FrameworkResponse & {
  body?: unknown;
};

function createResponse(): TestResponse {
  return {
    committed: false,
    headers: {},
    redirect(status, location) {
      this.setStatus(status);
      this.setHeader('Location', location);
      this.committed = true;
    },
    send(body) {
      if (body !== undefined && readHeader(this, 'content-type') === undefined) {
        this.setHeader(
          'Content-Type',
          typeof body === 'string'
            ? 'text/plain; charset=utf-8'
            : 'application/json; charset=utf-8',
        );
      }
      this.body = body;
      this.committed = true;
    },
    setHeader(name, value) {
      const existingName = Object.keys(this.headers)
        .find((headerName) => headerName.toLowerCase() === name.toLowerCase());
      this.headers[existingName ?? name] = value;
    },
    setStatus(code) {
      this.statusCode = code;
      this.statusSet = true;
    },
    statusCode: undefined,
    statusSet: false,
  };
}

function createRequest(
  method: FrameworkRequest['method'],
  headers: FrameworkRequest['headers'] = {},
): FrameworkRequest {
  return {
    body: undefined,
    cookies: {},
    headers,
    method,
    params: {},
    path: '/documents/1',
    query: {},
    raw: {},
    url: '/documents/1',
  };
}

function readHeader(response: FrameworkResponse, name: string): string | undefined {
  const entry = Object.entries(response.headers)
    .find(([headerName]) => headerName.toLowerCase() === name.toLowerCase());
  return typeof entry?.[1] === 'string' ? entry[1] : undefined;
}

describe('dispatcher conditional request policy', () => {
  it('generates a strong ETag and uses weak comparison for If-None-Match', async () => {
    @Controller('/documents')
    class DocumentsController {
      @Get('/:id')
      read() {
        return { id: '1', revision: 3 };
      }
    }

    const root = new Container().register(DocumentsController);
    const dispatcher = createDispatcher({
      conditionalRequests: {
        etag: 'strong',
      },
      handlerMapping: createHandlerMapping([{ controllerToken: DocumentsController }]),
      rootContainer: root,
    });
    const initialResponse = createResponse();

    // Given: a successful representation whose strong validator is generated by the dispatcher.
    await dispatcher.dispatch(createRequest('GET'), initialResponse);
    const etag = readHeader(initialResponse, 'etag');

    // When: a later GET presents the same opaque tag as a weak validator.
    const conditionalResponse = createResponse();
    await dispatcher.dispatch(createRequest('GET', {
      'if-none-match': etag === undefined ? undefined : `W/${etag}`,
    }), conditionalResponse);

    // Then: weak comparison selects a bodyless 304 and preserves the selected validator.
    expect(etag).toMatch(/^"sha256-[0-9a-f]{64}"$/);
    expect(conditionalResponse.statusCode).toBe(304);
    expect(conditionalResponse.body).toBeUndefined();
    expect(readHeader(conditionalResponse, 'etag')).toBe(etag);
  });

  it('requires strong comparison for If-Match before an unsafe handler runs', async () => {
    let writes = 0;

    @Controller('/documents')
    class DocumentsController {
      @Put('/:id')
      update() {
        writes += 1;
        return { updated: true };
      }
    }

    const root = new Container().register(DocumentsController);
    const dispatcher = createDispatcher({
      conditionalRequests: {
        resolve() {
          return { etag: 'W/"revision-3"' };
        },
      },
      handlerMapping: createHandlerMapping([{ controllerToken: DocumentsController }]),
      rootContainer: root,
    });
    const response = createResponse();

    // Given: the current representation only has a weak validator.
    // When: an unsafe request requires the same opaque tag through If-Match.
    await dispatcher.dispatch(createRequest('PUT', {
      'if-match': '"revision-3"',
    }), response);

    // Then: strong comparison fails before the handler can mutate state.
    expect(response.statusCode).toBe(412);
    expect(response.body).toBeUndefined();
    expect(writes).toBe(0);
  });

  it('gives If-Match precedence over If-Unmodified-Since', async () => {
    let writes = 0;

    @Controller('/documents')
    class DocumentsController {
      @Put('/:id')
      update() {
        writes += 1;
        return { updated: true };
      }
    }

    const root = new Container().register(DocumentsController);
    const dispatcher = createDispatcher({
      conditionalRequests: {
        resolve() {
          return {
            etag: '"revision-3"',
            lastModified: '2026-08-25T10:15:30.900Z',
          };
        },
      },
      handlerMapping: createHandlerMapping([{ controllerToken: DocumentsController }]),
      rootContainer: root,
    });
    const response = createResponse();

    // Given: If-Match succeeds while the older date precondition would fail.
    // When: the unsafe request is dispatched.
    await dispatcher.dispatch(createRequest('PUT', {
      'if-match': '"revision-3"',
      'if-unmodified-since': 'Mon, 24 Aug 2026 10:15:30 GMT',
    }), response);

    // Then: entity-tag precedence allows the handler and normalizes Last-Modified.
    expect(response.statusCode).toBe(200);
    expect(writes).toBe(1);
    expect(readHeader(response, 'last-modified')).toBe('Tue, 25 Aug 2026 10:15:30 GMT');
  });

  it('gives If-None-Match precedence over If-Modified-Since', async () => {
    let reads = 0;

    @Controller('/documents')
    class DocumentsController {
      @Get('/:id')
      read() {
        reads += 1;
        return { id: '1' };
      }
    }

    const root = new Container().register(DocumentsController);
    const dispatcher = createDispatcher({
      conditionalRequests: {
        resolve() {
          return {
            etag: '"revision-3"',
            lastModified: 'Tue, 25 Aug 2026 10:15:30 GMT',
          };
        },
      },
      handlerMapping: createHandlerMapping([{ controllerToken: DocumentsController }]),
      rootContainer: root,
    });
    const response = createResponse();

    // Given: If-None-Match does not match while the later date would select 304.
    // When: the request is dispatched with both validators.
    await dispatcher.dispatch(createRequest('GET', {
      'if-modified-since': 'Wed, 26 Aug 2026 10:15:30 GMT',
      'if-none-match': '"another-revision"',
    }), response);

    // Then: entity-tag precedence ignores the date and executes the handler.
    expect(response.statusCode).toBe(200);
    expect(reads).toBe(1);
    expect(response.body).toEqual({ id: '1' });
  });

  it('evaluates date preconditions when entity-tag fields are absent', async () => {
    let calls = 0;

    @Controller('/documents')
    class DocumentsController {
      @Get('/:id')
      read() {
        calls += 1;
        return { id: '1' };
      }

      @Put('/:id')
      update() {
        calls += 1;
        return { updated: true };
      }
    }

    const root = new Container().register(DocumentsController);
    const dispatcher = createDispatcher({
      conditionalRequests: {
        resolve() {
          return {
            lastModified: 'Tue, 25 Aug 2026 10:15:30 GMT',
          };
        },
      },
      handlerMapping: createHandlerMapping([{ controllerToken: DocumentsController }]),
      rootContainer: root,
    });
    const notModifiedResponse = createResponse();
    const preconditionFailedResponse = createResponse();

    // Given: the dispatcher knows the representation's normalized modification time.
    // When: safe and unsafe methods present date-only preconditions.
    await dispatcher.dispatch(createRequest('GET', {
      'if-modified-since': 'Tue, 25 Aug 2026 10:15:30 GMT',
    }), notModifiedResponse);
    await dispatcher.dispatch(createRequest('PUT', {
      'if-unmodified-since': 'Mon, 24 Aug 2026 10:15:30 GMT',
    }), preconditionFailedResponse);

    // Then: the safe request receives 304 and the unsafe request receives 412 before side effects.
    expect(notModifiedResponse.statusCode).toBe(304);
    expect(preconditionFailedResponse.statusCode).toBe(412);
    expect(notModifiedResponse.body).toBeUndefined();
    expect(preconditionFailedResponse.body).toBeUndefined();
    expect(calls).toBe(0);
  });

  it('selects bodyless 304 and 412 outcomes before handler execution', async () => {
    let calls = 0;

    @Controller('/documents')
    class DocumentsController {
      @Get('/:id')
      read() {
        calls += 1;
        return { id: '1' };
      }

      @Put('/:id')
      update() {
        calls += 1;
        return { updated: true };
      }
    }

    const root = new Container().register(DocumentsController);
    const dispatcher = createDispatcher({
      conditionalRequests: {
        resolve({ requestContext }) {
          requestContext.response.setHeader('Cache-Control', 'private, max-age=0');
          requestContext.response.setHeader('Vary', 'Accept-Encoding');
          return {
            etag: '"revision-3"',
            lastModified: '2026-08-25T10:15:30.900Z',
          };
        },
      },
      handlerMapping: createHandlerMapping([{ controllerToken: DocumentsController }]),
      rootContainer: root,
    });

    // Given: one current representation with cache metadata.
    // When: safe and unsafe requests present matching If-None-Match validators.
    const notModifiedResponse = createResponse();
    await dispatcher.dispatch(createRequest('GET', {
      'if-none-match': 'W/"revision-3"',
    }), notModifiedResponse);
    const preconditionFailedResponse = createResponse();
    await dispatcher.dispatch(createRequest('PUT', {
      'if-none-match': '"revision-3"',
    }), preconditionFailedResponse);

    // Then: both outcomes suppress bodies, preserve metadata, and skip handlers.
    expect(notModifiedResponse.statusCode).toBe(304);
    expect(preconditionFailedResponse.statusCode).toBe(412);
    expect(notModifiedResponse.body).toBeUndefined();
    expect(preconditionFailedResponse.body).toBeUndefined();
    expect(readHeader(notModifiedResponse, 'etag')).toBe('"revision-3"');
    expect(readHeader(notModifiedResponse, 'last-modified')).toBe('Tue, 25 Aug 2026 10:15:30 GMT');
    expect(readHeader(notModifiedResponse, 'cache-control')).toBe('private, max-age=0');
    expect(readHeader(notModifiedResponse, 'vary')).toBe('Accept-Encoding');
    expect(calls).toBe(0);
  });

  it('keeps HEAD metadata identical to GET while suppressing its body', async () => {
    const representation = { id: '1', revision: 3 };

    @Controller('/documents')
    class DocumentsController {
      @Get('/:id')
      read() {
        return representation;
      }

      @Head('/:id')
      inspect() {
        return representation;
      }
    }

    const root = new Container().register(DocumentsController);
    const dispatcher = createDispatcher({
      conditionalRequests: {
        etag: 'weak',
      },
      handlerMapping: createHandlerMapping([{ controllerToken: DocumentsController }]),
      rootContainer: root,
    });
    const getResponse = createResponse();
    const headResponse = createResponse();

    // Given: GET and HEAD select the same representation.
    // When: both methods are dispatched through the shared response policy.
    await dispatcher.dispatch(createRequest('GET'), getResponse);
    await dispatcher.dispatch(createRequest('HEAD'), headResponse);

    // Then: metadata matches and HEAD writes no body.
    expect(readHeader(headResponse, 'etag')).toBe(readHeader(getResponse, 'etag'));
    expect(readHeader(headResponse, 'content-type')).toBe(readHeader(getResponse, 'content-type'));
    expect(readHeader(headResponse, 'etag')).toMatch(/^W\/"sha256-[0-9a-f]{64}"$/);
    expect(headResponse.statusCode).toBe(200);
    expect(headResponse.body).toBeUndefined();
  });

  it('does not generate validators for Cache-Control no-store responses', async () => {
    @Controller('/documents')
    class DocumentsController {
      @Get('/:id')
      read(_input: undefined, context: { response: FrameworkResponse }) {
        context.response.setHeader('Cache-Control', 'no-store');
        return { secret: true };
      }
    }

    const root = new Container().register(DocumentsController);
    const dispatcher = createDispatcher({
      conditionalRequests: {
        etag: 'strong',
      },
      handlerMapping: createHandlerMapping([{ controllerToken: DocumentsController }]),
      rootContainer: root,
    });
    const response = createResponse();

    await dispatcher.dispatch(createRequest('GET'), response);

    expect(response.statusCode).toBe(200);
    expect(readHeader(response, 'etag')).toBeUndefined();
    expect(response.body).toEqual({ secret: true });
  });
});
