import { VersioningType } from '@fluojs/http/portable';

import type { ReactPageCatalogEntry } from './page-catalog.js';
import { parseGeneratedReactPageCatalog } from './typegen-artifact.js';
import { parseReactTypegenContracts, type ReactTypegenContracts, renderReactTypegenContracts } from './typegen-contract.js';
import { type ReactJsonShape, renderReactJsonType } from './typegen-projection.js';
import { renderReactContractRuntime } from './typegen-runtime.js';

export { createHttpTypeProjection } from '@fluojs/http/internal';
export type { ReactFormTypeProjection, ReactTypegenContracts } from './typegen-contract.js';
export type { ReactJsonField, ReactJsonShape, ReactQueryField } from './typegen-projection.js';

/** Current schema version embedded in generated React page type artifacts. */
export const REACT_PAGE_TYPEGEN_ARTIFACT_VERSION = 2;

const GENERATED_BANNER = `/* Generated by @fluojs/react/typegen. Artifact version: ${REACT_PAGE_TYPEGEN_ARTIFACT_VERSION}. Do not edit manually. */`;
const GENERATED_FOOTER = '/* End generated @fluojs/react/typegen artifact. */';
const GENERATED_BANNER_PATTERN = /^\/\* Generated by @fluojs\/react\/typegen\. Artifact version: (0|[1-9][0-9]{0,8})\. Do not edit manually\. \*\/\r?\n/u;

/** Structural classification of an existing React page type artifact. */
export type ReactPageTypeArtifactInspection =
  | { readonly status: 'malformed' }
  | { readonly status: 'unsupported-version'; readonly version: number }
  | { readonly status: 'valid'; readonly version: number };

/** Stable diagnostic codes emitted by React page type generation. */
export const REACT_PAGE_TYPEGEN_ERROR_CODES = {
  VERSIONED_ROUTE_UNSUPPORTED: 'react-page-typegen-versioned-route-unsupported',
} as const;

/** Diagnostic code emitted by React page type generation. */
export type ReactPageTypegenErrorCode = (typeof REACT_PAGE_TYPEGEN_ERROR_CODES)[keyof typeof REACT_PAGE_TYPEGEN_ERROR_CODES];

/** Typed failure raised when a catalog entry cannot be represented by path-only output. */
export class ReactPageTypegenError extends Error {
  readonly name = 'ReactPageTypegenError';
  readonly code: ReactPageTypegenErrorCode = REACT_PAGE_TYPEGEN_ERROR_CODES.VERSIONED_ROUTE_UNSUPPORTED;

  constructor(readonly routeId: string) {
    super(`Versioned React page route "${routeId}" is unsupported by path-only typegen.`);
  }
}

/**
 * Classifies generated React page type source before tooling compares its bytes.
 *
 * @param source Existing artifact source read from disk.
 * @returns Its current, malformed, or unsupported-version structural status.
 */
export function inspectReactPageTypeArtifact(source: string): ReactPageTypeArtifactInspection {
  const match = GENERATED_BANNER_PATTERN.exec(source);
  const rawVersion = match?.[1];
  if (rawVersion === undefined) {
    return { status: 'malformed' };
  }

  const version = Number(rawVersion);
  if (version !== REACT_PAGE_TYPEGEN_ARTIFACT_VERSION) {
    return { status: 'unsupported-version', version };
  }

  const normalizedSource = source.replaceAll('\r\n', '\n');
  const parsedCatalog = parseGeneratedReactPageCatalog(normalizedSource);
  const contracts = parseReactTypegenContracts(normalizedSource);
  if (
    parsedCatalog === undefined
    || contracts === null
    || !normalizedSource.endsWith(`${GENERATED_FOOTER}\n`)
    || generateReactPageTypes(parsedCatalog, contracts) !== normalizedSource
  ) {
    return { status: 'malformed' };
  }

  return { status: 'valid', version };
}

function stringLiteral(value: string): string {
  return JSON.stringify(value);
}

function renderPathMap(catalog: readonly ReactPageCatalogEntry[]): string[] {
  if (catalog.length === 0) {
    return ['export type ReactPagePathById = Readonly<Record<never, never>>;'];
  }

  return [
    'export interface ReactPagePathById {',
    ...catalog.map((entry) => `  readonly ${stringLiteral(entry.id)}: ${stringLiteral(entry.path)};`),
    '}',
  ];
}

function uniqueParams(entry: ReactPageCatalogEntry): readonly string[] {
  return [...new Set(entry.params)];
}

function renderParamsMap(catalog: readonly ReactPageCatalogEntry[]): string[] {
  if (catalog.length === 0) {
    return ['export type ReactPageParamsById = Readonly<Record<never, never>>;'];
  }

  const lines = ['export interface ReactPageParamsById {'];
  for (const entry of catalog) {
    const params = uniqueParams(entry);
    if (params.length === 0) {
      lines.push(`  readonly ${stringLiteral(entry.id)}: undefined;`);
      continue;
    }

    lines.push(`  readonly ${stringLiteral(entry.id)}: {`);
    lines.push(...params.map((param) => `    readonly ${stringLiteral(param)}: string;`));
    lines.push('  };');
  }
  lines.push('}');
  return lines;
}

function renderHrefExpression(entry: ReactPageCatalogEntry): string {
  const path = renderPathExpression(entry);
  if (entry.query === undefined || entry.query.length === 0) return path;
  const bindings = entry.query.map((field) => {
    const value = `query[${stringLiteral(field.property)}]`;
    const scalar = `search.append(${stringLiteral(field.wire)}, value);`;
    const array = `for (const item of value) search.append(${stringLiteral(field.wire)}, item);`;
    const kind = wireKind(field.shape);
    const append = kind === 'scalar' ? scalar : kind === 'array' ? array
      : `if (typeof value === 'string') ${scalar} else ${array}`;
    return `{ const value = ${value}; if (value !== undefined) { ${append} } }`;
  }).join(' ');
  return `(() => { const search = new URLSearchParams(); if (query !== undefined) { ${bindings} } const encoded = search.toString(); return ${path} + (encoded === '' ? '' : '?' + encoded); })()`;
}

function wireKind(shape: ReactJsonShape): 'scalar' | 'array' | 'mixed' {
  if (shape.kind === 'array') return 'array';
  if (shape.kind !== 'union') return 'scalar';
  const kinds = new Set(shape.members.map(wireKind));
  return kinds.size === 1 ? wireKind(shape.members[0]) : 'mixed';
}

function renderPathExpression(entry: ReactPageCatalogEntry): string {
  const params = uniqueParams(entry);
  if (params.length === 0) {
    return stringLiteral(entry.path);
  }

  const paramNames = new Set(params);
  const parts = entry.path.split('/').slice(1).flatMap((segment) => {
    const paramName = segment.startsWith(':') ? segment.slice(1) : undefined;
    if (paramName !== undefined && paramNames.has(paramName)) {
      return [stringLiteral('/'), `encodeURIComponent(params[${stringLiteral(paramName)}])`];
    }

    return [stringLiteral(`/${segment}`)];
  });

  return `[${parts.join(', ')}].join('')`;
}

function renderParameters(entry: ReactPageCatalogEntry, leadingParameter?: string): string {
  if (entry.query !== undefined && entry.query.length > 0) {
    const generics: string[] = [];
    const parameters: string[] = leadingParameter === undefined ? [] : [leadingParameter];
    if (uniqueParams(entry).length > 0) {
      const expected = `ReactPageParamsById[${stringLiteral(entry.id)}]`;
      generics.push(`Actual extends ${expected}`);
      parameters.push(`params: Actual & Record<Actual extends ${expected} ? Exclude<keyof Actual, keyof ${expected}> : never, never>`);
    }
    const query = `ReactPageQueryById[${stringLiteral(entry.id)}]`;
    generics.push(`QueryActual extends ${query}`);
    parameters.push(`query${entry.query.every((field) => field.optional) ? '?' : ''}: QueryActual & Record<QueryActual extends ${query} ? Exclude<keyof QueryActual, keyof ${query}> : never, never>`);
    return `<${generics.join(', ')}>(${parameters.join(', ')})`;
  }
  if (uniqueParams(entry).length === 0) {
    return `(${leadingParameter ?? ''})`;
  }

  const expected = `ReactPageParamsById[${stringLiteral(entry.id)}]`;
  const prefix = leadingParameter === undefined ? '' : `${leadingParameter}, `;
  return `<Actual extends ${expected}>(${prefix}params: Actual & Record<Actual extends ${expected} ? Exclude<keyof Actual, keyof ${expected}> : never, never>)`;
}

function renderQueryMap(catalog: readonly ReactPageCatalogEntry[], contracts?: ReactTypegenContracts): string[] {
  if (!catalog.some((entry) => (entry.query?.length ?? 0) > 0)) return [];
  return [
    ...(contracts === undefined
      ? ['export type ReactJsonValue = null | string | number | boolean | readonly ReactJsonValue[] | { readonly [key: string]: ReactJsonValue };'] : []),
    'export interface ReactPageQueryById {',
    ...catalog.map((entry) => `  readonly ${stringLiteral(entry.id)}: ${renderReactJsonType({
      kind: 'object',
      fields: Object.fromEntries((entry.query ?? []).map((field) => [field.property, field])),
    })};`),
    '}',
  ];
}

function renderHref(entry: ReactPageCatalogEntry): string {
  return `href: ${renderParameters(entry)}: string => ${renderHrefExpression(entry)}`;
}

function renderLink(entry: ReactPageCatalogEntry): string {
  return `link: ${renderParameters(entry)}: ReactPageLinkProps => ({ href: ${renderHrefExpression(entry)} })`;
}

function renderNavigation(entry: ReactPageCatalogEntry, operation: 'push' | 'replace'): string {
  const parameters = renderParameters(entry, 'navigator: ReactPageNavigator');
  return `${operation}: ${parameters}: void => navigator.${operation}(${renderHrefExpression(entry)})`;
}

function renderRoutes(catalog: readonly ReactPageCatalogEntry[]): string[] {
  const lines = ['export const reactPageRoutes = {'];
  for (const entry of catalog) {
    lines.push(`  ${stringLiteral(entry.id)}: {`);
    lines.push(`    id: ${stringLiteral(entry.id)},`);
    lines.push(`    path: ${stringLiteral(entry.path)},`);
    lines.push(`    ${renderHref(entry)},`);
    lines.push(`    ${renderLink(entry)},`);
    lines.push(`    ${renderNavigation(entry, 'push')},`);
    lines.push(`    ${renderNavigation(entry, 'replace')},`);
    lines.push('  },');
  }
  lines.push('} as const;');
  return lines;
}

/**
 * Generates path-only TypeScript route declarations and href builders from a React page catalog.
 *
 * @param catalog Bootstrap-resolved React page catalog entries.
 * @param projection Optional frozen compiler module/form contracts from the same application.
 * @returns Deterministic TypeScript source for application-owned route tooling.
 */
export function generateReactPageTypes(catalog: readonly ReactPageCatalogEntry[], projection?: ReactTypegenContracts): string {
  for (const entry of catalog) {
    if (entry.version !== undefined && entry.versionSelection !== VersioningType.URI) {
      throw new ReactPageTypegenError(entry.id);
    }
  }

  const sortedCatalog = [...catalog].sort((left, right) => {
    if (left.id < right.id) {
      return -1;
    }
    if (left.id > right.id) {
      return 1;
    }
    return 0;
  });
  const contracts = projection === undefined ? undefined : {
    ...(projection.sourceFingerprint === undefined ? {} : { sourceFingerprint: projection.sourceFingerprint }),
    modules: Object.fromEntries(Object.entries(projection.modules).sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)),
    forms: [...projection.forms].sort((left, right) => left.id < right.id ? -1 : left.id > right.id ? 1 : 0),
  };

  return [
    GENERATED_BANNER,
    '',
    ...(contracts === undefined ? [] : [
      renderReactTypegenContracts(contracts),
      ...renderReactContractRuntime(contracts),
    ]),
    `export type ReactPageRouteId = ${sortedCatalog.length === 0 ? 'never' : sortedCatalog.map((entry) => stringLiteral(entry.id)).join(' | ')};`,
    ...renderPathMap(sortedCatalog),
    ...renderParamsMap(sortedCatalog),
    ...renderQueryMap(sortedCatalog, contracts),
    ...(sortedCatalog.some((entry) => entry.query !== undefined || entry.sourceFingerprint !== undefined)
      ? [`// fluo-type-projection ${JSON.stringify(sortedCatalog.map((entry) => ({
        id: entry.id,
        ...(entry.query === undefined ? {} : { query: entry.query }),
        ...(entry.sourceFingerprint === undefined ? {} : { sourceFingerprint: entry.sourceFingerprint }),
      })))}`] : []),
    'export type ReactPagePath<RouteId extends ReactPageRouteId> = ReactPagePathById[RouteId];',
    'export type ReactPageParams<RouteId extends ReactPageRouteId> = ReactPageParamsById[RouteId];',
    '/** Real-anchor props produced by one generated React page route. */',
    'export type ReactPageLinkProps = { readonly href: string; };',
    '/** Minimal HTTP-first router surface consumed by generated push and replace methods. */',
    'export interface ReactPageNavigator {',
    '  readonly push: (href: string) => void;',
    '  readonly replace: (href: string) => void;',
    '}',
    ...renderRoutes(sortedCatalog),
    'export type ReactPageRoute = (typeof reactPageRoutes)[ReactPageRouteId];',
    GENERATED_FOOTER,
    '',
  ].join('\n');
}
