import type { ReactPageCatalogEntry } from './page-catalog.js';

const GENERATED_BANNER = '/* Generated by @fluojs/react/typegen. Do not edit manually. */';

/** Stable diagnostic codes emitted by React page type generation. */
export const REACT_PAGE_TYPEGEN_ERROR_CODES = {
  VERSIONED_ROUTE_UNSUPPORTED: 'react-page-typegen-versioned-route-unsupported',
} as const;

/** Diagnostic code emitted by React page type generation. */
export type ReactPageTypegenErrorCode = (typeof REACT_PAGE_TYPEGEN_ERROR_CODES)[keyof typeof REACT_PAGE_TYPEGEN_ERROR_CODES];

/** Typed failure raised when a catalog entry cannot be represented by path-only output. */
export class ReactPageTypegenError extends Error {
  readonly name = 'ReactPageTypegenError';
  readonly code: ReactPageTypegenErrorCode = REACT_PAGE_TYPEGEN_ERROR_CODES.VERSIONED_ROUTE_UNSUPPORTED;

  constructor(readonly routeId: string) {
    super(`Versioned React page route "${routeId}" is unsupported by path-only typegen.`);
  }
}

function stringLiteral(value: string): string {
  return JSON.stringify(value);
}

function renderPathMap(catalog: readonly ReactPageCatalogEntry[]): string[] {
  if (catalog.length === 0) {
    return ['export type ReactPagePathById = Readonly<Record<never, never>>;'];
  }

  return [
    'export interface ReactPagePathById {',
    ...catalog.map((entry) => `  readonly ${stringLiteral(entry.id)}: ${stringLiteral(entry.path)};`),
    '}',
  ];
}

function uniqueParams(entry: ReactPageCatalogEntry): readonly string[] {
  return [...new Set(entry.params)];
}

function renderParamsMap(catalog: readonly ReactPageCatalogEntry[]): string[] {
  if (catalog.length === 0) {
    return ['export type ReactPageParamsById = Readonly<Record<never, never>>;'];
  }

  const lines = ['export interface ReactPageParamsById {'];
  for (const entry of catalog) {
    const params = uniqueParams(entry);
    if (params.length === 0) {
      lines.push(`  readonly ${stringLiteral(entry.id)}: undefined;`);
      continue;
    }

    lines.push(`  readonly ${stringLiteral(entry.id)}: {`);
    lines.push(...params.map((param) => `    readonly ${stringLiteral(param)}: string;`));
    lines.push('  };');
  }
  lines.push('}');
  return lines;
}

function renderHrefExpression(entry: ReactPageCatalogEntry): string {
  const params = uniqueParams(entry);
  if (params.length === 0) {
    return stringLiteral(entry.path);
  }

  const paramNames = new Set(params);
  const parts = entry.path.split('/').slice(1).flatMap((segment) => {
    const paramName = segment.startsWith(':') ? segment.slice(1) : undefined;
    if (paramName !== undefined && paramNames.has(paramName)) {
      return [stringLiteral('/'), `encodeURIComponent(params[${stringLiteral(paramName)}])`];
    }

    return [stringLiteral(`/${segment}`)];
  });

  return `[${parts.join(', ')}].join('')`;
}

function renderParameters(entry: ReactPageCatalogEntry, leadingParameter?: string): string {
  if (uniqueParams(entry).length === 0) {
    return `(${leadingParameter ?? ''})`;
  }

  const expected = `ReactPageParamsById[${stringLiteral(entry.id)}]`;
  const prefix = leadingParameter === undefined ? '' : `${leadingParameter}, `;
  return `<Actual extends ${expected}>(${prefix}params: Actual & Record<Actual extends ${expected} ? Exclude<keyof Actual, keyof ${expected}> : never, never>)`;
}

function renderHref(entry: ReactPageCatalogEntry): string {
  return `href: ${renderParameters(entry)}: string => ${renderHrefExpression(entry)}`;
}

function renderLink(entry: ReactPageCatalogEntry): string {
  return `link: ${renderParameters(entry)}: ReactPageLinkProps => ({ href: ${renderHrefExpression(entry)} })`;
}

function renderNavigation(entry: ReactPageCatalogEntry, operation: 'push' | 'replace'): string {
  const parameters = renderParameters(entry, 'navigator: ReactPageNavigator');
  return `${operation}: ${parameters}: void => navigator.${operation}(${renderHrefExpression(entry)})`;
}

function renderRoutes(catalog: readonly ReactPageCatalogEntry[]): string[] {
  const lines = ['export const reactPageRoutes = {'];
  for (const entry of catalog) {
    lines.push(`  ${stringLiteral(entry.id)}: {`);
    lines.push(`    id: ${stringLiteral(entry.id)},`);
    lines.push(`    path: ${stringLiteral(entry.path)},`);
    lines.push(`    ${renderHref(entry)},`);
    lines.push(`    ${renderLink(entry)},`);
    lines.push(`    ${renderNavigation(entry, 'push')},`);
    lines.push(`    ${renderNavigation(entry, 'replace')},`);
    lines.push('  },');
  }
  lines.push('} as const;');
  return lines;
}

/**
 * Generates path-only TypeScript route declarations and href builders from a React page catalog.
 *
 * @param catalog Bootstrap-resolved React page catalog entries.
 * @returns Deterministic TypeScript source for application-owned route tooling.
 */
export function generateReactPageTypes(catalog: readonly ReactPageCatalogEntry[]): string {
  for (const entry of catalog) {
    if (entry.version !== undefined) {
      throw new ReactPageTypegenError(entry.id);
    }
  }

  const sortedCatalog = [...catalog].sort((left, right) => {
    if (left.id < right.id) {
      return -1;
    }
    if (left.id > right.id) {
      return 1;
    }
    return 0;
  });

  return [
    GENERATED_BANNER,
    '',
    `export type ReactPageRouteId = ${sortedCatalog.length === 0 ? 'never' : sortedCatalog.map((entry) => stringLiteral(entry.id)).join(' | ')};`,
    ...renderPathMap(sortedCatalog),
    ...renderParamsMap(sortedCatalog),
    'export type ReactPagePath<RouteId extends ReactPageRouteId> = ReactPagePathById[RouteId];',
    'export type ReactPageParams<RouteId extends ReactPageRouteId> = ReactPageParamsById[RouteId];',
    '/** Real-anchor props produced by one generated React page route. */',
    'export type ReactPageLinkProps = { readonly href: string; };',
    '/** Minimal HTTP-first router surface consumed by generated push and replace methods. */',
    'export interface ReactPageNavigator {',
    '  readonly push: (href: string) => void;',
    '  readonly replace: (href: string) => void;',
    '}',
    ...renderRoutes(sortedCatalog),
    'export type ReactPageRoute = (typeof reactPageRoutes)[ReactPageRouteId];',
    '',
  ].join('\n');
}
