import { readFileSync } from 'node:fs';

import { createHandlerMapping, FromQuery, Optional, RequestDto, Version } from '@fluojs/http';
import ts from 'typescript';
import { describe, expect, it } from 'vitest';

import { Path, Router } from './decorators.js';
import type { ReactPageCatalogEntry } from './page-catalog.js';
import { createReactPageCatalog } from './page-catalog.js';
import {
  generateReactPageTypes,
  inspectReactPageTypeArtifact,
  REACT_PAGE_TYPEGEN_ARTIFACT_VERSION,
} from './typegen.js';

const catalog = [
  {
    handler: 'index',
    id: 'GET /products ProductRouter index',
    kind: 'react-page',
    method: 'GET',
    params: [],
    path: '/products',
    router: 'ProductRouter',
  },
  {
    handler: 'show',
    id: 'GET /products/:productId ProductRouter show',
    kind: 'react-page',
    method: 'GET',
    params: ['productId'],
    path: '/products/:productId',
    router: 'ProductRouter',
  },
] satisfies readonly ReactPageCatalogEntry[];

describe('@fluojs/react/typegen', () => {
  it('encodes aliased optional and repeated query without changing artifact inspection', () => {
    // Given: a query projection preserves HTTP field aliases and materialization.
    class SearchInput {
      @FromQuery('q')
      term = '';

      @Optional()
      @FromQuery('tag')
      tags: string | readonly string[] = [];
    }
    @Router('/search')
    class SearchRouter {
      @Path()
      @RequestDto(SearchInput)
      show(_input: SearchInput): void {}
    }
    const mapping = createHandlerMapping([{ controllerToken: SearchRouter }]);
    const pages = createReactPageCatalog(mapping.descriptors).map((entry) => ({
      ...entry,
      query: [
        { property: 'term', wire: 'q', optional: false, shape: { kind: 'string' as const } },
        { property: 'tags', wire: 'tag', optional: true, shape: { kind: 'array' as const, item: { kind: 'string' as const } } },
      ],
    }));

    // When: a standalone generated builder receives actual wire text.
    const source = generateReactPageTypes(pages);
    const javascript = ts.transpileModule(source, {
      compilerOptions: { module: ts.ModuleKind.CommonJS },
    }).outputText;
    const exports: { reactPageRoutes?: Record<string, { href: (query: { term: string; tags?: readonly string[] }) => string }> } = {};
    new Function('exports', javascript)(exports);
    const href = exports.reactPageRoutes?.['GET /search SearchRouter show']?.href({
      term: '한 글+/%', tags: ['', 'a+b', 'a/b'],
    });

    // Then: native query decoding retains text, order, duplicates and empty values.
    expect(href).toBe('/search?q=%ED%95%9C+%EA%B8%80%2B%2F%25&tag=&tag=a%2Bb&tag=a%2Fb');
    const query = new URL(href ?? '', 'https://example.test').searchParams;
    expect(query.get('q')).toBe('한 글+/%');
    expect(query.getAll('tag')).toEqual(['', 'a+b', 'a/b']);
    expect(query.has('term')).toBe(false);
    expect(inspectReactPageTypeArtifact(source)).toEqual({
      status: 'valid', version: REACT_PAGE_TYPEGEN_ARTIFACT_VERSION,
    });
  });

  it('generates URI-versioned hrefs only from compiled selection provenance', () => {
    // Given: HTTP compiles a versioned page using its default URI strategy.
    @Router('/items')
    class ItemsRouter {
      @Version('2')
      @Path('/:id')
      show(): void {}
    }
    const mapping = createHandlerMapping([{ controllerToken: ItemsRouter }]);

    // When: the existing generator evaluates the authoritative catalog.
    const source = generateReactPageTypes(createReactPageCatalog(mapping.descriptors));
    const javascript = ts.transpileModule(source, {
      compilerOptions: { module: ts.ModuleKind.CommonJS },
    }).outputText;
    const exports: { reactPageRoutes?: Record<string, { href: (params: { id: string }) => string }> } = {};
    new Function('exports', javascript)(exports);
    const href = exports.reactPageRoutes?.['GET /v2/items/:id ItemsRouter show']?.href({ id: 'a/b' });

    // Then: the generated URL resolves to the same compiled handler.
    expect(href).toBe('/v2/items/a%2Fb');
    const match = mapping.match({
      cookies: {}, headers: {}, method: 'GET', params: {},
      path: '/v2/items/a%2Fb', query: {}, raw: {}, url: '/v2/items/a%2Fb',
    });
    expect(match?.descriptor).toBe(mapping.descriptors[0]);
    expect(inspectReactPageTypeArtifact(source)).toEqual({
      status: 'valid', version: REACT_PAGE_TYPEGEN_ARTIFACT_VERSION,
    });
  });

  it('emits and recognizes the current deterministic artifact version', () => {
    // Given: one authoritative React page catalog.
    const pages = catalog;

    // When: typegen renders and inspects its own artifact.
    const output = generateReactPageTypes(pages);
    const inspection = inspectReactPageTypeArtifact(output);

    // Then: the first line identifies the stable artifact schema and inspection accepts it.
    expect(output.split('\n', 1)).toEqual([
      `/* Generated by @fluojs/react/typegen. Artifact version: ${REACT_PAGE_TYPEGEN_ARTIFACT_VERSION}. Do not edit manually. */`,
    ]);
    expect(inspection).toEqual({
      status: 'valid',
      version: REACT_PAGE_TYPEGEN_ARTIFACT_VERSION,
    });
  });

  it('distinguishes malformed artifacts from unsupported artifact versions', () => {
    // Given: one current artifact truncated after its required declarations and one complete artifact from a future schema.
    const complete = generateReactPageTypes(catalog);
    const malformed = complete.slice(0, complete.indexOf(`  ${JSON.stringify(catalog[0].id)}: {`));
    const unsupported = complete.replace(
      `Artifact version: ${REACT_PAGE_TYPEGEN_ARTIFACT_VERSION}.`,
      'Artifact version: 99.',
    );

    // When: tooling inspects both artifacts before deciding whether they are stale.
    const malformedInspection = inspectReactPageTypeArtifact(malformed);
    const unsupportedInspection = inspectReactPageTypeArtifact(unsupported);

    // Then: corruption and a newer schema remain separate actionable states.
    expect(malformedInspection).toEqual({ status: 'malformed' });
    expect(unsupportedInspection).toEqual({ status: 'unsupported-version', version: 99 });
  });

  it('classifies a syntactically malformed current-version body as malformed', () => {
    // Given: a current-version artifact keeps its banner, sentinels, and footer but has invalid TypeScript syntax.
    const malformed = generateReactPageTypes(catalog).replace(
      'export const reactPageRoutes = {',
      'export const reactPageRoutes = {]',
    );

    // When: tooling validates the complete generated body.
    const inspection = inspectReactPageTypeArtifact(malformed);

    // Then: syntax corruption is malformed rather than a valid stale artifact.
    expect(inspection).toEqual({ status: 'malformed' });
  });

  it('generates absolute paths and href builders with required params', () => {
    // Given
    const pages = catalog;

    // When
    const output = generateReactPageTypes(pages);

    // Then
    expect(output).toContain('export type ReactPageRouteId =');
    expect(output).toContain('readonly "GET /products ProductRouter index": "/products";');
    expect(output).toContain('readonly "GET /products/:productId ProductRouter show": {');
    expect(output).toContain('readonly "productId": string;');
    expect(output).toContain('href: (): string => "/products"');
    expect(output).toContain('href: <Actual extends ReactPageParamsById["GET /products/:productId ProductRouter show"]>');
    expect(output).toContain('encodeURIComponent(params["productId"])');
  });

  it('generates route-bound Link props and push or replace authoring methods', () => {
    // Given
    const pages = catalog;

    // When
    const output = generateReactPageTypes(pages);

    // Then
    expect(output).toContain('export type ReactPageLinkProps = { readonly href: string; };');
    expect(output).toContain('export interface ReactPageNavigator {');
    expect(output).toContain('link: (): ReactPageLinkProps => ({ href: "/products" })');
    expect(output).toContain('push: (navigator: ReactPageNavigator): void => navigator.push("/products")');
    expect(output).toContain('replace: (navigator: ReactPageNavigator): void => navigator.replace("/products")');
    expect(output).toContain('link: <Actual extends ReactPageParamsById["GET /products/:productId ProductRouter show"]>');
    expect(output).toContain('push: <Actual extends ReactPageParamsById["GET /products/:productId ProductRouter show"]>');
    expect(output).toContain('replace: <Actual extends ReactPageParamsById["GET /products/:productId ProductRouter show"]>');
    expect(output).toContain('params: Actual & Record<Actual extends ReactPageParamsById["GET /products/:productId ProductRouter show"] ? Exclude<keyof Actual, keyof ReactPageParamsById["GET /products/:productId ProductRouter show"]> : never, never>');
  });

  it('keeps output deterministic when catalog registration order changes', () => {
    // Given
    const reversedPages = [...catalog].reverse();

    // When
    const first = generateReactPageTypes(catalog);
    const second = generateReactPageTypes(reversedPages);

    // Then
    expect(second).toBe(first);
  });

  it('orders canonically equivalent Unicode ids by code units regardless of registration order', () => {
    // Given
    const composedPage = {
      ...catalog[0],
      id: 'GET /caf\u00e9 CafeRouter show',
      path: '/caf\u00e9',
      router: 'CafeRouter',
    } satisfies ReactPageCatalogEntry;
    const decomposedPage = {
      ...catalog[0],
      id: 'GET /cafe\u0301 CafeRouter show',
      path: '/cafe\u0301',
      router: 'CafeRouter',
    } satisfies ReactPageCatalogEntry;

    // When
    const first = generateReactPageTypes([composedPage, decomposedPage]);
    const second = generateReactPageTypes([decomposedPage, composedPage]);

    // Then
    expect(second).toBe(first);
    expect(first.indexOf(JSON.stringify(decomposedPage.id))).toBeLessThan(first.indexOf(JSON.stringify(composedPage.id)));
  });

  it('rejects versioned pages instead of erasing non-path dispatch requirements', () => {
    // Given
    const versionedCatalog = [
      {
        ...catalog[0],
        id: 'GET /v2/products ProductRouter index',
        path: '/v2/products',
        version: '2',
      },
    ] satisfies readonly ReactPageCatalogEntry[];

    // When
    const action = () => generateReactPageTypes(versionedCatalog);

    // Then
    expect(action).toThrow(expect.objectContaining({
      code: 'react-page-typegen-versioned-route-unsupported',
      routeId: 'GET /v2/products ProductRouter index',
    }));
  });

  it('publishes typegen from a tooling subpath without widening the runtime-neutral root', async () => {
    // Given
    const packageManifest = readFileSync(new URL('../package.json', import.meta.url), 'utf8');

    // When
    const root = await import('./index.js');
    const typegen = await import('./typegen.js');

    // Then
    expect(packageManifest).toContain('"./typegen"');
    expect(root).not.toHaveProperty('generateReactPageTypes');
    expect(typegen.generateReactPageTypes).toBe(generateReactPageTypes);
  });
});
