import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import ts from 'typescript';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { I18nError } from './errors.js';
import {
  generateI18nCatalogTypes,
  generateI18nCatalogTypesFromDirectory,
  type I18nCatalogTypegenDirectoryOptions,
  type I18nCatalogTypegenInput,
  type I18nCatalogTypegenOptions,
} from './typegen.js';
import type { I18nErrorCode, I18nMessageTree } from './types.js';

let rootDir: string;

function expectI18nThrow(action: () => unknown, code: I18nErrorCode): void {
  try {
    action();
  } catch (error) {
    expect(error).toBeInstanceOf(I18nError);
    expect((error as I18nError).code).toBe(code);
    return;
  }

  throw new Error(`Expected action to fail with ${code}.`);
}

async function expectI18nRejection(action: () => Promise<unknown>, code: I18nErrorCode): Promise<void> {
  try {
    await action();
  } catch (error) {
    expect(error).toBeInstanceOf(I18nError);
    expect((error as I18nError).code).toBe(code);
    return;
  }

  throw new Error(`Expected action to fail with ${code}.`);
}

async function writeCatalog(locale: string, namespace: string, catalog: unknown): Promise<void> {
  const namespaceParts = namespace.split('/');
  const fileName = `${namespaceParts.pop() ?? namespace}.json`;
  const directory = join(rootDir, locale, ...namespaceParts);

  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, fileName), JSON.stringify(catalog), 'utf8');
}

describe('@fluojs/i18n/typegen', () => {
  beforeEach(async () => {
    rootDir = await mkdtemp(join(tmpdir(), 'fluo-i18n-typegen-'));
  });

  afterEach(async () => {
    await rm(rootDir, { force: true, recursive: true });
  });

  it('generates fully qualified key unions for root and namespaced nested catalogs', () => {
    const output = generateI18nCatalogTypes([
      {
        locale: 'en',
        messages: {
          app: {
            title: 'Welcome',
          },
        },
      },
      {
        locale: 'en',
        messages: {
          cancel: 'Cancel',
          nested: {
            save: 'Save',
          },
        },
        namespace: 'admin/common',
      },
    ]);

    expect(output).toContain('export type I18nCatalogKey = "admin/common.cancel" | "admin/common.nested.save" | "app.title";');
    expect(output).toContain('export type I18nCatalogNamespace = "admin/common";');
    expect(output).toContain('readonly "admin/common": "cancel" | "nested.save";');
  });

  it('includes own __proto__ message keys in generated catalog declarations', () => {
    // Given: an in-memory catalog with an own key that collides with Object.prototype.
    const messages: I18nMessageTree = {};
    Object.defineProperty(messages, '__proto__', { enumerable: true, value: 'Prototype-safe' });

    // When: typegen snapshots and traverses the catalog.
    const output = generateI18nCatalogTypes([{ locale: 'en', messages }]);

    // Then: the valid own key appears in the generated union.
    expect(output).toContain('export type I18nCatalogKey = "__proto__";');
  });

  it('rejects cyclic in-memory catalogs with the stable invalid catalog code', () => {
    // Given: an in-memory catalog whose nested tree refers to itself.
    const messages: Record<string, string | I18nMessageTree> = {};
    messages.self = messages;

    // When/Then: typegen validation reports the documented error instead of overflowing recursion.
    expectI18nThrow(() => generateI18nCatalogTypes([{ locale: 'en', messages }]), 'I18N_INVALID_CATALOG');
  });

  it('reads locale namespace files from disk using deterministic namespace paths', async () => {
    await writeCatalog('ko', 'common/actions', { save: '저장' });
    await writeCatalog('en', 'common/actions', { cancel: 'Cancel', save: 'Save' });
    await writeCatalog('en', 'root', { app: { title: 'Welcome' } });

    const output = await generateI18nCatalogTypesFromDirectory({ rootDir });

    expect(output).toEqual(`/* Generated by @fluojs/i18n/typegen. Do not edit manually. */

export type I18nCatalogKey = "common/actions.cancel" | "common/actions.save" | "root.app.title";
export type I18nCatalogNamespace = "common/actions" | "root";
export interface I18nCatalogKeyByNamespace {
  readonly "common/actions": "cancel" | "save";
  readonly "root": "app.title";
}
export type I18nCatalogNamespaceKey<Namespace extends I18nCatalogNamespace> = I18nCatalogKeyByNamespace[Namespace];
export type I18nCatalogTypedTranslateOptions = Omit<import('@fluojs/i18n').I18nTranslateOptions, 'namespace'>;
export type I18nCatalogTypedTranslate = <Key extends I18nCatalogKey>(
  key: Key,
  options: I18nCatalogTypedTranslateOptions,
) => string;
export interface I18nCatalogTypedService {
  readonly translate: I18nCatalogTypedTranslate;
  readonly translateInNamespace: <
    Namespace extends I18nCatalogNamespace,
    Key extends I18nCatalogNamespaceKey<Namespace>,
  >(
    namespace: Namespace,
    key: Key,
    options: Omit<import('@fluojs/i18n').I18nTranslateOptions, 'namespace'>,
  ) => string;
}
`);
  });

  it('generates opt-in typed helper surfaces for fully qualified and namespace-scoped keys', () => {
    const output = generateI18nCatalogTypes(
      [
        {
          locale: 'en',
          messages: {
            dashboard: {
              title: 'Dashboard',
            },
          },
          namespace: 'admin/common',
        },
      ],
      {
        keyTypeName: 'AppI18nKey',
        keyByNamespaceTypeName: 'AppI18nKeysByNamespace',
        namespaceKeyTypeName: 'AppI18nNamespaceKey',
        namespaceTypeName: 'AppI18nNamespace',
        typedServiceTypeName: 'AppTypedI18n',
        typedTranslateOptionsTypeName: 'AppTypedTranslateOptions',
        typedTranslateTypeName: 'AppTypedTranslate',
      },
    );

    expect(output).toContain('export type AppI18nKey = "admin/common.dashboard.title";');
    expect(output).toContain('export type AppI18nNamespaceKey<Namespace extends AppI18nNamespace> = AppI18nKeysByNamespace[Namespace];');
    expect(output).toContain("export type AppTypedTranslateOptions = Omit<import('@fluojs/i18n').I18nTranslateOptions, 'namespace'>;");
    expect(output).toContain('export type AppTypedTranslate = <Key extends AppI18nKey>(');
    expect(output).toContain('options: AppTypedTranslateOptions,');
    expect(output).toContain('readonly translate: AppTypedTranslate;');
    expect(output).toContain('Namespace extends AppI18nNamespace,');
    expect(output).toContain('Key extends AppI18nNamespaceKey<Namespace>,');
  });

  it('compiles generated declarations for valid callsites and rejects invalid keys', async () => {
    // Given: valid and invalid consumers import the declaration text emitted by the production type generator.
    const declarations = generateI18nCatalogTypes([
      { locale: 'en', messages: { dashboard: { title: 'Dashboard' } }, namespace: 'admin/common' },
      { locale: 'en', messages: { cancel: 'Cancel' }, namespace: 'common' },
    ]);
    const i18nModulePath = join(rootDir, 'i18n-module.d.ts');
    const validConsumerPath = join(rootDir, 'valid-consumer.ts');
    const invalidConsumerPath = join(rootDir, 'invalid-consumer.ts');
    await Promise.all([
      writeFile(join(rootDir, 'generated-i18n-catalog.d.ts'), declarations, 'utf8'),
      writeFile(
        i18nModulePath,
        "declare module '@fluojs/i18n' { export interface I18nTranslateOptions { readonly locale: string; readonly namespace?: string; } }",
        'utf8',
      ),
      writeFile(
        validConsumerPath,
        [
          "import type { I18nCatalogTypedService } from './generated-i18n-catalog.d.ts';",
          'declare const typedI18n: I18nCatalogTypedService;',
          "typedI18n.translate('admin/common.dashboard.title', { locale: 'en' });",
          "typedI18n.translate('common.cancel', { locale: 'en' });",
          "typedI18n.translateInNamespace('admin/common', 'dashboard.title', { locale: 'en' });",
          "typedI18n.translateInNamespace('common', 'cancel', { locale: 'en' });",
        ].join('\n'),
        'utf8',
      ),
      writeFile(
        invalidConsumerPath,
        [
          "import type { I18nCatalogTypedService } from './generated-i18n-catalog.d.ts';",
          'declare const typedI18n: I18nCatalogTypedService;',
          "typedI18n.translate('admin/common.dashboard.missing', { locale: 'en' });",
          "typedI18n.translateInNamespace('common', 'dashboard.title', { locale: 'en' });",
        ].join('\n'),
        'utf8',
      ),
    ]);

    // When: one TypeScript program compiles both consumers with that exact generated declaration file.
    const program = ts.createProgram({
      options: {
        lib: ['lib.es5.d.ts'],
        module: ts.ModuleKind.ESNext,
        moduleResolution: ts.ModuleResolutionKind.Bundler,
        noEmit: true,
        strict: true,
        target: ts.ScriptTarget.ES2022,
        types: [],
        verbatimModuleSyntax: true,
      },
      rootNames: [i18nModulePath, validConsumerPath, invalidConsumerPath],
    });
    const diagnostics = ts.getPreEmitDiagnostics(program);

    // Then: only invalid fully qualified and namespace-scoped keys produce diagnostics.
    expect(diagnostics.map((diagnostic) => ({ code: diagnostic.code, file: diagnostic.file?.fileName }))).toEqual([
      { code: 2345, file: invalidConsumerPath },
      { code: 2345, file: invalidConsumerPath },
    ]);
  });

  it('keeps generated output stable regardless of input order and duplicate locale leaves', () => {
    const first = generateI18nCatalogTypes([
      { locale: 'ko', messages: { beta: '베타', nested: { zeta: '제타' } } },
      { locale: 'en', messages: { alpha: 'Alpha', nested: { zeta: 'Zeta' } } },
    ]);
    const second = generateI18nCatalogTypes([
      { locale: 'en', messages: { nested: { zeta: 'Zeta' }, alpha: 'Alpha' } },
      { locale: 'ko', messages: { nested: { zeta: '제타' }, beta: '베타' } },
    ]);

    expect(first).toBe(second);
    expect(first).toContain('export type I18nCatalogKey = "alpha" | "beta" | "nested.zeta";');
  });

  it('fails with stable errors for invalid inputs, catalogs, namespaces, and options', async () => {
    expectI18nThrow(
      () => generateI18nCatalogTypes([{ locale: 'en', messages: { count: 1 } as unknown as I18nMessageTree }]),
      'I18N_INVALID_CATALOG',
    );
    expectI18nThrow(
      () => generateI18nCatalogTypes([{ locale: 'en', messages: { title: 'Welcome' }, namespace: '../common' }]),
      'I18N_INVALID_LOADER_OPTIONS',
    );
    expectI18nThrow(
      () => generateI18nCatalogTypes(null as unknown as readonly I18nCatalogTypegenInput[]),
      'I18N_INVALID_OPTIONS',
    );
    expectI18nThrow(
      () => generateI18nCatalogTypes([], { keyTypeName: 'not-valid-name' } as I18nCatalogTypegenOptions),
      'I18N_INVALID_OPTIONS',
    );
    await expectI18nRejection(
      () => generateI18nCatalogTypesFromDirectory({ rootDir: '' } as I18nCatalogTypegenDirectoryOptions),
      'I18N_INVALID_OPTIONS',
    );

    await writeCatalog('en', 'invalid', { enabled: true });
    await expectI18nRejection(() => generateI18nCatalogTypesFromDirectory({ rootDir }), 'I18N_INVALID_CATALOG');
  });

  it('is available from the typegen subpath without adding root value exports', async () => {
    const root = await import('./index.js');
    const typegen = await import('./typegen.js');

    expect(Object.keys(root).sort()).toEqual(['I18nError', 'I18nModule', 'I18nService', 'createI18n']);
    expect(typegen.generateI18nCatalogTypes).toBe(generateI18nCatalogTypes);
    expect(typegen.generateI18nCatalogTypes([{ locale: 'en', messages: { title: 'Welcome' } }])).toContain('"title"');
  });
});
