import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { I18nError } from './errors.js';
import type { I18nErrorCode, I18nMessageTree } from './types.js';
import {
  generateI18nCatalogTypes,
  generateI18nCatalogTypesFromDirectory,
  type I18nCatalogTypegenDirectoryOptions,
  type I18nCatalogTypegenInput,
  type I18nCatalogTypegenOptions,
} from './typegen.js';

let rootDir: string;

function expectI18nThrow(action: () => unknown, code: I18nErrorCode): void {
  try {
    action();
  } catch (error) {
    expect(error).toBeInstanceOf(I18nError);
    expect((error as I18nError).code).toBe(code);
    return;
  }

  throw new Error(`Expected action to fail with ${code}.`);
}

async function expectI18nRejection(action: () => Promise<unknown>, code: I18nErrorCode): Promise<void> {
  try {
    await action();
  } catch (error) {
    expect(error).toBeInstanceOf(I18nError);
    expect((error as I18nError).code).toBe(code);
    return;
  }

  throw new Error(`Expected action to fail with ${code}.`);
}

async function writeCatalog(locale: string, namespace: string, catalog: unknown): Promise<void> {
  const namespaceParts = namespace.split('/');
  const fileName = `${namespaceParts.pop() ?? namespace}.json`;
  const directory = join(rootDir, locale, ...namespaceParts);

  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, fileName), JSON.stringify(catalog), 'utf8');
}

describe('@fluojs/i18n/typegen', () => {
  beforeEach(async () => {
    rootDir = await mkdtemp(join(tmpdir(), 'fluo-i18n-typegen-'));
  });

  afterEach(async () => {
    await rm(rootDir, { force: true, recursive: true });
  });

  it('generates fully qualified key unions for root and namespaced nested catalogs', () => {
    const output = generateI18nCatalogTypes([
      {
        locale: 'en',
        messages: {
          app: {
            title: 'Welcome',
          },
        },
      },
      {
        locale: 'en',
        messages: {
          cancel: 'Cancel',
          nested: {
            save: 'Save',
          },
        },
        namespace: 'admin/common',
      },
    ]);

    expect(output).toContain('export type I18nCatalogKey = "admin/common.cancel" | "admin/common.nested.save" | "app.title";');
    expect(output).toContain('export type I18nCatalogNamespace = "admin/common";');
    expect(output).toContain('readonly "admin/common": "cancel" | "nested.save";');
  });

  it('reads locale namespace files from disk using deterministic namespace paths', async () => {
    await writeCatalog('ko', 'common/actions', { save: '저장' });
    await writeCatalog('en', 'common/actions', { cancel: 'Cancel', save: 'Save' });
    await writeCatalog('en', 'root', { app: { title: 'Welcome' } });

    const output = await generateI18nCatalogTypesFromDirectory({ rootDir });

    expect(output).toEqual(`/* Generated by @fluojs/i18n/typegen. Do not edit manually. */

export type I18nCatalogKey = "common/actions.cancel" | "common/actions.save" | "root.app.title";
export type I18nCatalogNamespace = "common/actions" | "root";
export interface I18nCatalogKeyByNamespace {
  readonly "common/actions": "cancel" | "save";
  readonly "root": "app.title";
}
`);
  });

  it('keeps generated output stable regardless of input order and duplicate locale leaves', () => {
    const first = generateI18nCatalogTypes([
      { locale: 'ko', messages: { beta: '베타', nested: { zeta: '제타' } } },
      { locale: 'en', messages: { alpha: 'Alpha', nested: { zeta: 'Zeta' } } },
    ]);
    const second = generateI18nCatalogTypes([
      { locale: 'en', messages: { nested: { zeta: 'Zeta' }, alpha: 'Alpha' } },
      { locale: 'ko', messages: { nested: { zeta: '제타' }, beta: '베타' } },
    ]);

    expect(first).toBe(second);
    expect(first).toContain('export type I18nCatalogKey = "alpha" | "beta" | "nested.zeta";');
  });

  it('fails with stable errors for invalid inputs, catalogs, namespaces, and options', async () => {
    expectI18nThrow(
      () => generateI18nCatalogTypes([{ locale: 'en', messages: { count: 1 } as unknown as I18nMessageTree }]),
      'I18N_INVALID_CATALOG',
    );
    expectI18nThrow(
      () => generateI18nCatalogTypes([{ locale: 'en', messages: { title: 'Welcome' }, namespace: '../common' }]),
      'I18N_INVALID_LOADER_OPTIONS',
    );
    expectI18nThrow(
      () => generateI18nCatalogTypes(null as unknown as readonly I18nCatalogTypegenInput[]),
      'I18N_INVALID_OPTIONS',
    );
    expectI18nThrow(
      () => generateI18nCatalogTypes([], { keyTypeName: 'not-valid-name' } as I18nCatalogTypegenOptions),
      'I18N_INVALID_OPTIONS',
    );
    await expectI18nRejection(
      () => generateI18nCatalogTypesFromDirectory({ rootDir: '' } as I18nCatalogTypegenDirectoryOptions),
      'I18N_INVALID_OPTIONS',
    );

    await writeCatalog('en', 'invalid', { enabled: true });
    await expectI18nRejection(() => generateI18nCatalogTypesFromDirectory({ rootDir }), 'I18N_INVALID_CATALOG');
  });

  it('is available from the typegen subpath without adding root value exports', async () => {
    const root = await import('./index.js');
    const typegen = await import('./typegen.js');

    expect(Object.keys(root).sort()).toEqual(['I18nError', 'I18nModule', 'I18nService', 'createI18n']);
    expect(typegen.generateI18nCatalogTypes).toBe(generateI18nCatalogTypes);
    expect(typegen.generateI18nCatalogTypes([{ locale: 'en', messages: { title: 'Welcome' } }])).toContain('"title"');
  });
});
