import { readdir, readFile } from 'node:fs/promises';
import { extname, join, relative, sep } from 'node:path';

import { I18nError } from './errors.js';
import { isPlainObject, snapshotLoaderMessageTree, validateLoaderLocale, validateLoaderNamespace } from './loaders/shared.js';
import type { I18nLocale, I18nMessageTree, I18nTranslationKey } from './types.js';

const DEFAULT_BANNER = '/* Generated by @fluojs/i18n/typegen. Do not edit manually. */';
const DEFAULT_KEY_TYPE_NAME = 'I18nCatalogKey';
const DEFAULT_NAMESPACE_TYPE_NAME = 'I18nCatalogNamespace';
const DEFAULT_KEY_BY_NAMESPACE_TYPE_NAME = 'I18nCatalogKeyByNamespace';
const DEFAULT_NAMESPACE_KEY_TYPE_NAME = 'I18nCatalogNamespaceKey';
const DEFAULT_TYPED_TRANSLATE_OPTIONS_TYPE_NAME = 'I18nCatalogTypedTranslateOptions';
const DEFAULT_TYPED_TRANSLATE_TYPE_NAME = 'I18nCatalogTypedTranslate';
const DEFAULT_TYPED_SERVICE_TYPE_NAME = 'I18nCatalogTypedService';
const IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

type CatalogEntry = {
  readonly locale: I18nLocale;
  readonly namespace?: I18nTranslationKey;
  readonly messages: I18nMessageTree;
};

/**
 * Catalog input consumed by the i18n catalog type generator.
 */
export interface I18nCatalogTypegenInput {
  /** Locale that owns this catalog tree. */
  readonly locale: I18nLocale;
  /** Optional filesystem or remote loader namespace path, for example `common` or `admin/common`. */
  readonly namespace?: I18nTranslationKey;
  /** Nested message tree whose string leaves become generated translation keys. */
  readonly messages: I18nMessageTree;
}

/**
 * Options for rendering TypeScript declarations from catalog inputs.
 */
export interface I18nCatalogTypegenOptions {
  /** Banner written at the top of the generated declaration output. */
  readonly banner?: string;
  /** Exported union type name for fully qualified translation keys. */
  readonly keyTypeName?: string;
  /** Exported union type name for discovered namespace paths. */
  readonly namespaceTypeName?: string;
  /** Exported mapped type name that stores leaf keys by namespace path. */
  readonly keyByNamespaceTypeName?: string;
  /** Exported helper type name that resolves leaf keys for a namespace path. */
  readonly namespaceKeyTypeName?: string;
  /** Exported options type name for fully qualified typed translation calls. */
  readonly typedTranslateOptionsTypeName?: string;
  /** Exported callable type name for fully qualified key translation. */
  readonly typedTranslateTypeName?: string;
  /** Exported facade type name for opt-in typed translation callsites. */
  readonly typedServiceTypeName?: string;
}

/**
 * Options for loading JSON catalog files from a locale/namespace directory tree before type generation.
 */
export interface I18nCatalogTypegenDirectoryOptions extends I18nCatalogTypegenOptions {
  /** Root directory containing locale directories and nested JSON namespace files. */
  readonly rootDir: string;
  /** Optional locale allow-list. When omitted, all immediate directories under `rootDir` are scanned. */
  readonly locales?: readonly I18nLocale[];
}

function assertIdentifier(value: string | undefined, fallback: string, label: string): string {
  const name = value ?? fallback;
  if (!IDENTIFIER_PATTERN.test(name)) {
    throw new I18nError(`${label} must be a valid TypeScript identifier.`, 'I18N_INVALID_OPTIONS');
  }

  return name;
}

function normalizeBanner(value: string | undefined): string {
  if (value === undefined) {
    return DEFAULT_BANNER;
  }

  if (typeof value !== 'string') {
    throw new I18nError('Catalog typegen banner must be a string when provided.', 'I18N_INVALID_OPTIONS');
  }

  return value;
}

function assertDirectoryOptions(options: I18nCatalogTypegenDirectoryOptions): void {
  if (!isPlainObject(options) || typeof options.rootDir !== 'string' || options.rootDir.trim() === '') {
    throw new I18nError('Catalog typegen rootDir must be a non-empty string.', 'I18N_INVALID_OPTIONS');
  }

  if (options.locales !== undefined) {
    if (!Array.isArray(options.locales)) {
      throw new I18nError('Catalog typegen locales must be an array when provided.', 'I18N_INVALID_OPTIONS');
    }

    for (const locale of options.locales) {
      validateLoaderLocale(locale, 'Catalog typegen');
    }
  }
}

function normalizeInput(input: I18nCatalogTypegenInput): CatalogEntry {
  if (!isPlainObject(input)) {
    throw new I18nError('Catalog typegen input must be a plain object.', 'I18N_INVALID_OPTIONS');
  }

  validateLoaderLocale(input.locale, 'Catalog typegen');
  if (input.namespace !== undefined) {
    validateLoaderNamespace(input.namespace, 'Catalog typegen');
  }

  return {
    locale: input.locale,
    messages: snapshotLoaderMessageTree(input.messages, `catalogs.${input.locale}${input.namespace === undefined ? '' : `.${input.namespace}`}`),
    namespace: input.namespace,
  };
}

function collectLeafKeys(tree: I18nMessageTree, prefix = ''): string[] {
  const keys: string[] = [];

  for (const key of Object.keys(tree).sort()) {
    const value = tree[key];
    const nextPrefix = prefix === '' ? key : `${prefix}.${key}`;

    if (typeof value === 'string') {
      keys.push(nextPrefix);
    } else {
      keys.push(...collectLeafKeys(value, nextPrefix));
    }
  }

  return keys;
}

function unionLiteral(values: readonly string[]): string {
  if (values.length === 0) {
    return 'never';
  }

  return values.map((value) => JSON.stringify(value)).join(' | ');
}

function renderNamespaceMap(typeName: string, entries: ReadonlyMap<string, readonly string[]>): string[] {
  if (entries.size === 0) {
    return [`export type ${typeName} = Record<never, never>;`];
  }

  const lines = [`export interface ${typeName} {`];
  for (const namespace of [...entries.keys()].sort()) {
    lines.push(`  readonly ${JSON.stringify(namespace)}: ${unionLiteral(entries.get(namespace) ?? [])};`);
  }
  lines.push('}');
  return lines;
}

function renderTypedHelpers(names: {
  readonly keyTypeName: string;
  readonly namespaceTypeName: string;
  readonly keyByNamespaceTypeName: string;
  readonly namespaceKeyTypeName: string;
  readonly typedTranslateOptionsTypeName: string;
  readonly typedTranslateTypeName: string;
  readonly typedServiceTypeName: string;
}): string[] {
  return [
    `export type ${names.namespaceKeyTypeName}<Namespace extends ${names.namespaceTypeName}> = ${names.keyByNamespaceTypeName}[Namespace];`,
    `export type ${names.typedTranslateOptionsTypeName} = Omit<import('@fluojs/i18n').I18nTranslateOptions, 'namespace'>;`,
    `export type ${names.typedTranslateTypeName} = <Key extends ${names.keyTypeName}>(`,
    '  key: Key,',
    `  options: ${names.typedTranslateOptionsTypeName},`,
    ') => string;',
    `export interface ${names.typedServiceTypeName} {`,
    `  readonly translate: ${names.typedTranslateTypeName};`,
    '  readonly translateInNamespace: <',
    `    Namespace extends ${names.namespaceTypeName},`,
    `    Key extends ${names.namespaceKeyTypeName}<Namespace>,`,
    '  >(',
    '    namespace: Namespace,',
    '    key: Key,',
    "    options: Omit<import('@fluojs/i18n').I18nTranslateOptions, 'namespace'>,",
    '  ) => string;',
    '}',
  ];
}

function relativeJsonNamespace(localeDir: string, filePath: string): string {
  const relativePath = relative(localeDir, filePath).split(sep).join('/');
  return relativePath.slice(0, -extname(relativePath).length);
}

async function collectCatalogFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const entryPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectCatalogFiles(entryPath)));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith('.json')) {
      files.push(entryPath);
    }
  }

  return files;
}

async function readCatalogFile(locale: I18nLocale, namespace: I18nTranslationKey, filePath: string): Promise<I18nCatalogTypegenInput> {
  let parsed: unknown;
  try {
    parsed = JSON.parse(await readFile(filePath, 'utf8'));
  } catch {
    throw new I18nError(`Malformed i18n catalog JSON: ${locale}/${namespace}.json`, 'I18N_INVALID_CATALOG');
  }

  return { locale, messages: snapshotLoaderMessageTree(parsed, `catalogs.${locale}.${namespace}`), namespace };
}

/**
 * Generates deterministic TypeScript translation-key declarations from catalog message trees.
 *
 * @param inputs Locale and optional namespace catalog trees to inspect.
 * @param options Optional exported type names and output banner controls.
 * @returns TypeScript declaration text containing key and namespace helper types.
 * @throws {I18nError} When catalog inputs, namespaces, or output type names are invalid.
 */
export function generateI18nCatalogTypes(
  inputs: readonly I18nCatalogTypegenInput[],
  options: I18nCatalogTypegenOptions = {},
): string {
  if (!Array.isArray(inputs)) {
    throw new I18nError('Catalog typegen inputs must be an array.', 'I18N_INVALID_OPTIONS');
  }

  const keyTypeName = assertIdentifier(options.keyTypeName, DEFAULT_KEY_TYPE_NAME, 'Catalog typegen keyTypeName');
  const namespaceTypeName = assertIdentifier(options.namespaceTypeName, DEFAULT_NAMESPACE_TYPE_NAME, 'Catalog typegen namespaceTypeName');
  const keyByNamespaceTypeName = assertIdentifier(
    options.keyByNamespaceTypeName,
    DEFAULT_KEY_BY_NAMESPACE_TYPE_NAME,
    'Catalog typegen keyByNamespaceTypeName',
  );
  const namespaceKeyTypeName = assertIdentifier(
    options.namespaceKeyTypeName,
    DEFAULT_NAMESPACE_KEY_TYPE_NAME,
    'Catalog typegen namespaceKeyTypeName',
  );
  const typedTranslateTypeName = assertIdentifier(
    options.typedTranslateTypeName,
    DEFAULT_TYPED_TRANSLATE_TYPE_NAME,
    'Catalog typegen typedTranslateTypeName',
  );
  const typedTranslateOptionsTypeName = assertIdentifier(
    options.typedTranslateOptionsTypeName,
    DEFAULT_TYPED_TRANSLATE_OPTIONS_TYPE_NAME,
    'Catalog typegen typedTranslateOptionsTypeName',
  );
  const typedServiceTypeName = assertIdentifier(
    options.typedServiceTypeName,
    DEFAULT_TYPED_SERVICE_TYPE_NAME,
    'Catalog typegen typedServiceTypeName',
  );
  const keys = new Set<string>();
  const namespaces = new Set<string>();
  const keysByNamespace = new Map<string, Set<string>>();

  for (const input of inputs.map(normalizeInput)) {
    const leafKeys = collectLeafKeys(input.messages);
    const namespace = input.namespace;

    if (namespace !== undefined) {
      namespaces.add(namespace);
      const namespaceKeys = keysByNamespace.get(namespace) ?? new Set<string>();
      for (const leafKey of leafKeys) {
        namespaceKeys.add(leafKey);
        keys.add(`${namespace}.${leafKey}`);
      }
      keysByNamespace.set(namespace, namespaceKeys);
      continue;
    }

    for (const leafKey of leafKeys) {
      keys.add(leafKey);
    }
  }

  const sortedNamespaceMap = new Map<string, readonly string[]>();
  for (const namespace of [...keysByNamespace.keys()].sort()) {
    sortedNamespaceMap.set(namespace, [...(keysByNamespace.get(namespace) ?? [])].sort());
  }

  return [
    normalizeBanner(options.banner),
    '',
    `export type ${keyTypeName} = ${unionLiteral([...keys].sort())};`,
    `export type ${namespaceTypeName} = ${unionLiteral([...namespaces].sort())};`,
    ...renderNamespaceMap(keyByNamespaceTypeName, sortedNamespaceMap),
    ...renderTypedHelpers({
      keyByNamespaceTypeName,
      keyTypeName,
      namespaceKeyTypeName,
      namespaceTypeName,
      typedServiceTypeName,
      typedTranslateOptionsTypeName,
      typedTranslateTypeName,
    }),
    '',
  ].join('\n');
}

/**
 * Reads locale/namespace JSON catalogs from disk and generates deterministic TypeScript key declarations.
 *
 * @param options Directory scanning and output rendering options.
 * @returns TypeScript declaration text containing key and namespace helper types.
 * @throws {I18nError} When directory options, catalog JSON, namespaces, or message trees are invalid.
 */
export async function generateI18nCatalogTypesFromDirectory(options: I18nCatalogTypegenDirectoryOptions): Promise<string> {
  assertDirectoryOptions(options);

  const localeNames = options.locales === undefined ? (await readdir(options.rootDir, { withFileTypes: true })).filter((entry) => entry.isDirectory()).map((entry) => entry.name) : [...options.locales];
  const inputs: I18nCatalogTypegenInput[] = [];

  for (const locale of localeNames.sort()) {
    validateLoaderLocale(locale, 'Catalog typegen');
    const localeDir = join(options.rootDir, locale);

    for (const filePath of await collectCatalogFiles(localeDir)) {
      const namespace = relativeJsonNamespace(localeDir, filePath);
      validateLoaderNamespace(namespace, 'Catalog typegen');
      inputs.push(await readCatalogFile(locale, namespace, filePath));
    }
  }

  return generateI18nCatalogTypes(inputs, options);
}
